const items = [
  // Electronics
  {
    id: 1,
    name: "Smartphone",
    desc: "Latest 5G smartphone with AMOLED display.",
    price: 799.99,
    image: "https://picsum.photos/200?random=1",
    dateAdded: "2025-09-01",
    category: "Electronics",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Laptop",
    desc: "Powerful laptop with 16GB RAM and SSD storage.",
    price: 1199.99,
    image: "https://picsum.photos/200?random=2",
    dateAdded: "2025-09-01",
    category: "Electronics",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Wireless Headphones",
    desc: "Noise-cancelling headphones with 30-hour battery life.",
    price: 199.99,
    image: "https://picsum.photos/200?random=3",
    dateAdded: "2025-09-01",
    category: "Electronics",
    rating: 4.2,
  },
  {
    id: 4,
    name: "Smart Watch",
    desc: "Track your health and fitness with a sleek smartwatch.",
    price: 149.99,
    image: "https://picsum.photos/200?random=4",
    dateAdded: "2025-09-01",
    category: "Electronics",
    rating: 4.0,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    desc: "Portable speaker with deep bass and waterproof design.",
    price: 89.99,
    image: "https://picsum.photos/200?random=5",
    dateAdded: "2025-09-01",
    category: "Electronics",
    rating: 4.3,
  },

  // Clothes
  {
    id: 6,
    name: "T-Shirt",
    desc: "Cotton round-neck T-shirt with graphic print.",
    price: 19.99,
    image: "https://picsum.photos/200?random=6",
    dateAdded: "2025-09-02",
    category: "Clothes",
    rating: 4.1,
  },
  {
    id: 7,
    name: "Jeans",
    desc: "Slim fit blue denim jeans for everyday wear.",
    price: 49.99,
    image: "https://picsum.photos/200?random=7",
    dateAdded: "2025-09-02",
    category: "Clothes",
    rating: 4.4,
  },
  {
    id: 8,
    name: "Jacket",
    desc: "Stylish leather jacket with zipper pockets.",
    price: 129.99,
    image: "https://picsum.photos/200?random=8",
    dateAdded: "2025-09-02",
    category: "Clothes",
    rating: 4.6,
  },
  {
    id: 9,
    name: "Sneakers",
    desc: "Comfortable sneakers for casual and sports use.",
    price: 89.99,
    image: "https://picsum.photos/200?random=9",
    dateAdded: "2025-09-02",
    category: "Clothes",
    rating: 4.7,
  },
  {
    id: 10,
    name: "Hoodie",
    desc: "Soft fleece hoodie with adjustable drawstring.",
    price: 39.99,
    image: "https://picsum.photos/200?random=10",
    dateAdded: "2025-09-02",
    category: "Clothes",
    rating: 4.2,
  },

  // Food
  {
    id: 11,
    name: "Pizza",
    desc: "Cheese burst pizza with fresh toppings.",
    price: 12.99,
    image: "https://picsum.photos/200?random=11",
    dateAdded: "2025-09-03",
    category: "Food",
    rating: 4.9,
  },
  {
    id: 12,
    name: "Burger",
    desc: "Double patty burger with lettuce and cheese.",
    price: 8.99,
    image: "https://picsum.photos/200?random=12",
    dateAdded: "2025-09-03",
    category: "Food",
    rating: 4.6,
  },
  {
    id: 13,
    name: "Pasta",
    desc: "Italian pasta in creamy Alfredo sauce.",
    price: 10.99,
    image: "https://picsum.photos/200?random=13",
    dateAdded: "2025-09-03",
    category: "Food",
    rating: 4.3,
  },
  {
    id: 14,
    name: "Ice Cream",
    desc: "Vanilla ice cream with chocolate chips.",
    price: 5.99,
    image: "https://picsum.photos/200?random=14",
    dateAdded: "2025-09-03",
    category: "Food",
    rating: 4.8,
  },
  {
    id: 15,
    name: "Coffee",
    desc: "Freshly brewed cappuccino with milk foam.",
    price: 3.99,
    image: "https://picsum.photos/200?random=15",
    dateAdded: "2025-09-03",
    category: "Food",
    rating: 4.5,
  },

  // Home Appliances
  {
    id: 16,
    name: "Microwave Oven",
    desc: "20L digital microwave oven with auto cook.",
    price: 149.99,
    image: "https://picsum.photos/200?random=16",
    dateAdded: "2025-09-04",
    category: "Home Appliances",
    rating: 4.2,
  },
  {
    id: 17,
    name: "Refrigerator",
    desc: "Double door fridge with smart cooling technology.",
    price: 699.99,
    image: "https://picsum.photos/200?random=17",
    dateAdded: "2025-09-04",
    category: "Home Appliances",
    rating: 4.7,
  },
  {
    id: 18,
    name: "Washing Machine",
    desc: "Fully automatic washing machine with quick wash.",
    price: 499.99,
    image: "https://picsum.photos/200?random=18",
    dateAdded: "2025-09-04",
    category: "Home Appliances",
    rating: 4.6,
  },
  {
    id: 19,
    name: "Air Conditioner",
    desc: "1.5 ton split AC with inverter technology.",
    price: 799.99,
    image: "https://picsum.photos/200?random=19",
    dateAdded: "2025-09-04",
    category: "Home Appliances",
    rating: 4.4,
  },
  {
    id: 20,
    name: "Vacuum Cleaner",
    desc: "Compact vacuum cleaner with strong suction power.",
    price: 129.99,
    image: "https://picsum.photos/200?random=20",
    dateAdded: "2025-09-04",
    category: "Home Appliances",
    rating: 4.3,
  },

  // Sports & Fitness
  {
    id: 21,
    name: "Dumbbell Set",
    desc: "Adjustable dumbbells for home workouts.",
    price: 79.99,
    image: "https://picsum.photos/200?random=21",
    dateAdded: "2025-09-05",
    category: "Sports & Fitness",
    rating: 4.5,
  },
  {
    id: 22,
    name: "Yoga Mat",
    desc: "Non-slip yoga mat with extra cushioning.",
    price: 25.99,
    image: "https://picsum.photos/200?random=22",
    dateAdded: "2025-09-05",
    category: "Sports & Fitness",
    rating: 4.3,
  },
  {
    id: 23,
    name: "Treadmill",
    desc: "Foldable treadmill with speed control.",
    price: 499.99,
    image: "https://picsum.photos/200?random=23",
    dateAdded: "2025-09-05",
    category: "Sports & Fitness",
    rating: 4.6,
  },
  {
    id: 24,
    name: "Football",
    desc: "Durable leather football for outdoor play.",
    price: 29.99,
    image: "https://picsum.photos/200?random=24",
    dateAdded: "2025-09-05",
    category: "Sports & Fitness",
    rating: 4.1,
  },
  {
    id: 25,
    name: "Cycling Helmet",
    desc: "Lightweight helmet with ventilation for safety.",
    price: 59.99,
    image: "https://picsum.photos/200?random=25",
    dateAdded: "2025-09-05",
    category: "Sports & Fitness",
    rating: 4.4,
  },
];

export default items;
