const items = [
  // Electronics
  {
    id: 101,
    ProductName: "iPhone 16 Pro",
    ProductDesc: "Latest iPhone with A19 chip and titanium build.",
    Price: 129999,
    Image: "https://picsum.photos/200?random=101",
    dateAdded: "2025-09-01",
    Category: "Electronics",
    rating: 4.8,
  },
  {
    id: 102,
    ProductName: "Samsung Galaxy Z Fold 6",
    ProductDesc: "Foldable smartphone with cutting-edge design.",
    Price: 149999,
    Image: "https://picsum.photos/200?random=102",
    dateAdded: "2025-09-01",
    Category: "Electronics",
    rating: 4.6,
  },
  {
    id: 103,
    ProductName: "Sony WH-1000XM6",
    ProductDesc: "Noise-cancelling wireless headphones.",
    Price: 29999,
    Image: "https://picsum.photos/200?random=103",
    dateAdded: "2025-09-01",
    Category: "Electronics",
    rating: 4.7,
  },
  {
    id: 104,
    ProductName: "MacBook Air M4",
    ProductDesc: "Lightweight laptop with Apple M4 chip.",
    Price: 139999,
    Image: "https://picsum.photos/200?random=104",
    dateAdded: "2025-09-01",
    Category: "Electronics",
    rating: 4.9,
  },
  {
    id: 105,
    ProductName: "iPad Pro 14",
    ProductDesc: "Large screen iPad with OLED display.",
    Price: 89999,
    Image: "https://picsum.photos/200?random=105",
    dateAdded: "2025-09-01",
    Category: "Electronics",
    rating: 4.5,
  },
  {
    id: 106,
    ProductName: "Apple Watch X",
    ProductDesc: "Next-gen smartwatch with advanced health sensors.",
    Price: 49999,
    Image: "https://picsum.photos/200?random=106",
    dateAdded: "2025-09-06",
    Category: "Electronics",
    rating: 4.4,
  },
  {
    id: 107,
    ProductName: "Dell XPS 16",
    ProductDesc: "Premium ultrabook with OLED screen.",
    Price: 179999,
    Image: "https://picsum.photos/200?random=107",
    dateAdded: "2025-09-06",
    Category: "Electronics",
    rating: 4.7,
  },
  {
    id: 108,
    ProductName: "GoPro Hero 13",
    ProductDesc: "Action camera with 8K recording.",
    Price: 59999,
    Image: "https://picsum.photos/200?random=108",
    dateAdded: "2025-09-06",
    Category: "Electronics",
    rating: 4.5,
  },
  {
    id: 109,
    ProductName: "Nintendo Switch 2",
    ProductDesc: "Portable gaming console with 4K dock support.",
    Price: 39999,
    Image: "https://picsum.photos/200?random=109",
    dateAdded: "2025-09-06",
    Category: "Electronics",
    rating: 4.6,
  },
  {
    id: 110,
    ProductName: "Bose SoundLink Ultra",
    ProductDesc: "Premium Bluetooth speaker with deep bass.",
    Price: 25999,
    Image: "https://picsum.photos/200?random=110",
    dateAdded: "2025-09-06",
    Category: "Electronics",
    rating: 4.4,
  },

  // Clothes
  {
    id: 201,
    ProductName: "Graphic T-Shirt",
    ProductDesc: "Cotton T-shirt with modern print.",
    Price: 1999,
    Image: "https://picsum.photos/200?random=201",
    dateAdded: "2025-09-02",
    Category: "Clothes",
    rating: 4.2,
  },
  {
    id: 202,
    ProductName: "Denim Jeans",
    ProductDesc: "Slim fit stretchable denim.",
    Price: 3999,
    Image: "https://picsum.photos/200?random=202",
    dateAdded: "2025-09-02",
    Category: "Clothes",
    rating: 4.3,
  },
  {
    id: 203,
    ProductName: "Leather Jacket",
    ProductDesc: "Classic biker leather jacket.",
    Price: 9999,
    Image: "https://picsum.photos/200?random=203",
    dateAdded: "2025-09-02",
    Category: "Clothes",
    rating: 4.6,
  },
  {
    id: 204,
    ProductName: "Sneakers",
    ProductDesc: "White sneakers for casual wear.",
    Price: 4999,
    Image: "https://picsum.photos/200?random=204",
    dateAdded: "2025-09-02",
    Category: "Clothes",
    rating: 4.4,
  },
  {
    id: 205,
    ProductName: "Hoodie",
    ProductDesc: "Warm fleece hoodie with zipper.",
    Price: 2999,
    Image: "https://picsum.photos/200?random=205",
    dateAdded: "2025-09-02",
    Category: "Clothes",
    rating: 4.1,
  },
  {
    id: 206,
    ProductName: "Formal Shirt",
    ProductDesc: "Slim fit cotton formal shirt.",
    Price: 2499,
    Image: "https://picsum.photos/200?random=206",
    dateAdded: "2025-09-06",
    Category: "Clothes",
    rating: 4.2,
  },
  {
    id: 207,
    ProductName: "Track Pants",
    ProductDesc: "Comfortable joggers with stretch.",
    Price: 1999,
    Image: "https://picsum.photos/200?random=207",
    dateAdded: "2025-09-06",
    Category: "Clothes",
    rating: 4.3,
  },
  {
    id: 208,
    ProductName: "Casual Blazer",
    ProductDesc: "Lightweight blazer for parties.",
    Price: 5999,
    Image: "https://picsum.photos/200?random=208",
    dateAdded: "2025-09-06",
    Category: "Clothes",
    rating: 4.5,
  },
  {
    id: 209,
    ProductName: "Sports Shorts",
    ProductDesc: "Breathable polyester running shorts.",
    Price: 1299,
    Image: "https://picsum.photos/200?random=209",
    dateAdded: "2025-09-06",
    Category: "Clothes",
    rating: 4.1,
  },
  {
    id: 210,
    ProductName: "Winter Coat",
    ProductDesc: "Thick wool coat for cold weather.",
    Price: 7999,
    Image: "https://picsum.photos/200?random=210",
    dateAdded: "2025-09-06",
    Category: "Clothes",
    rating: 4.6,
  },

  // Food
  {
    id: 301,
    ProductName: "Margherita Pizza",
    ProductDesc: "Classic pizza with mozzarella cheese.",
    Price: 899,
    Image: "https://picsum.photos/200?random=301",
    dateAdded: "2025-09-03",
    Category: "Food",
    rating: 4.8,
  },
  {
    id: 302,
    ProductName: "Cheese Burger",
    ProductDesc: "Juicy beef burger with cheese slice.",
    Price: 499,
    Image: "https://picsum.photos/200?random=302",
    dateAdded: "2025-09-03",
    Category: "Food",
    rating: 4.6,
  },
  {
    id: 303,
    ProductName: "Pasta Alfredo",
    ProductDesc: "Creamy Alfredo pasta with herbs.",
    Price: 699,
    Image: "https://picsum.photos/200?random=303",
    dateAdded: "2025-09-03",
    Category: "Food",
    rating: 4.4,
  },
  {
    id: 304,
    ProductName: "Chocolate Ice Cream",
    ProductDesc: "Rich chocolate flavored ice cream.",
    Price: 299,
    Image: "https://picsum.photos/200?random=304",
    dateAdded: "2025-09-03",
    Category: "Food",
    rating: 4.9,
  },
  {
    id: 305,
    ProductName: "Latte Coffee",
    ProductDesc: "Freshly brewed latte with milk foam.",
    Price: 199,
    Image: "https://picsum.photos/200?random=305",
    dateAdded: "2025-09-03",
    Category: "Food",
    rating: 4.5,
  },
  {
    id: 306,
    ProductName: "Chicken Biryani",
    ProductDesc: "Spicy and flavorful biryani with chicken.",
    Price: 799,
    Image: "https://picsum.photos/200?random=306",
    dateAdded: "2025-09-06",
    Category: "Food",
    rating: 4.7,
  },
  {
    id: 307,
    ProductName: "Paneer Tikka",
    ProductDesc: "Grilled cottage cheese with spices.",
    Price: 599,
    Image: "https://picsum.photos/200?random=307",
    dateAdded: "2025-09-06",
    Category: "Food",
    rating: 4.4,
  },
  {
    id: 308,
    ProductName: "Caesar Salad",
    ProductDesc: "Fresh lettuce with Caesar dressing.",
    Price: 499,
    Image: "https://picsum.photos/200?random=308",
    dateAdded: "2025-09-06",
    Category: "Food",
    rating: 4.3,
  },
  {
    id: 309,
    ProductName: "Sushi Platter",
    ProductDesc: "Assorted sushi with wasabi and soy sauce.",
    Price: 1499,
    Image: "https://picsum.photos/200?random=309",
    dateAdded: "2025-09-06",
    Category: "Food",
    rating: 4.6,
  },
  {
    id: 310,
    ProductName: "Pancakes",
    ProductDesc: "Fluffy pancakes with maple syrup.",
    Price: 399,
    Image: "https://picsum.photos/200?random=310",
    dateAdded: "2025-09-06",
    Category: "Food",
    rating: 4.5,
  },

  // Home Appliances
  {
    id: 401,
    ProductName: "Microwave Oven",
    ProductDesc: "25L oven with smart controls.",
    Price: 11999,
    Image: "https://picsum.photos/200?random=401",
    dateAdded: "2025-09-04",
    Category: "Home Appliances",
    rating: 4.3,
  },
  {
    id: 402,
    ProductName: "Refrigerator",
    ProductDesc: "Smart inverter double door fridge.",
    Price: 54999,
    Image: "https://picsum.photos/200?random=402",
    dateAdded: "2025-09-04",
    Category: "Home Appliances",
    rating: 4.6,
  },
  {
    id: 403,
    ProductName: "Washing Machine",
    ProductDesc: "Automatic washing machine 7kg.",
    Price: 32999,
    Image: "https://picsum.photos/200?random=403",
    dateAdded: "2025-09-04",
    Category: "Home Appliances",
    rating: 4.5,
  },
  {
    id: 404,
    ProductName: "Air Conditioner",
    ProductDesc: "1.5 ton AC with turbo cooling.",
    Price: 42999,
    Image: "https://picsum.photos/200?random=404",
    dateAdded: "2025-09-04",
    Category: "Home Appliances",
    rating: 4.4,
  },
  {
    id: 405,
    ProductName: "Vacuum Cleaner",
    ProductDesc: "Bagless vacuum cleaner with HEPA filter.",
    Price: 7999,
    Image: "https://picsum.photos/200?random=405",
    dateAdded: "2025-09-04",
    Category: "Home Appliances",
    rating: 4.2,
  },
  {
    id: 406,
    ProductName: "Dishwasher",
    ProductDesc: "Automatic dishwasher with 14 place setting.",
    Price: 44999,
    Image: "https://picsum.photos/200?random=406",
    dateAdded: "2025-09-06",
    Category: "Home Appliances",
    rating: 4.5,
  },
  {
    id: 407,
    ProductName: "Water Purifier",
    ProductDesc: "RO + UV water purification system.",
    Price: 15999,
    Image: "https://picsum.photos/200?random=407",
    dateAdded: "2025-09-06",
    Category: "Home Appliances",
    rating: 4.4,
  },
  {
    id: 408,
    ProductName: "Induction Cooktop",
    ProductDesc: "Portable induction stove with touch controls.",
    Price: 5999,
    Image: "https://picsum.photos/200?random=408",
    dateAdded: "2025-09-06",
    Category: "Home Appliances",
    rating: 4.3,
  },
  {
    id: 409,
    ProductName: "Ceiling Fan",
    ProductDesc: "Energy-efficient ceiling fan with remote.",
    Price: 3499,
    Image: "https://picsum.photos/200?random=409",
    dateAdded: "2025-09-06",
    Category: "Home Appliances",
    rating: 4.2,
  },
  {
    id: 410,
    ProductName: "Mixer Grinder",
    ProductDesc: "750W mixer with 3 jars.",
    Price: 5999,
    Image: "https://picsum.photos/200?random=410",
    dateAdded: "2025-09-06",
    Category: "Home Appliances",
    rating: 4.5,
  },

  // Sports & Fitness
  {
    id: 501,
    ProductName: "Dumbbell Set",
    ProductDesc: "Adjustable dumbbells 20kg set.",
    Price: 4999,
    Image: "https://picsum.photos/200?random=501",
    dateAdded: "2025-09-05",
    Category: "Sports & Fitness",
    rating: 4.6,
  },
  {
    id: 502,
    ProductName: "Yoga Mat",
    ProductDesc: "Eco-friendly non-slip yoga mat.",
    Price: 1999,
    Image: "https://picsum.photos/200?random=502",
    dateAdded: "2025-09-05",
    Category: "Sports & Fitness",
    rating: 4.3,
  },
  {
    id: 503,
    ProductName: "Treadmill",
    ProductDesc: "Foldable treadmill with app control.",
    Price: 39999,
    Image: "https://picsum.photos/200?random=503",
    dateAdded: "2025-09-05",
    Category: "Sports & Fitness",
    rating: 4.7,
  },
  {
    id: 504,
    ProductName: "Football",
    ProductDesc: "Durable stitched football for outdoor.",
    Price: 999,
    Image: "https://picsum.photos/200?random=504",
    dateAdded: "2025-09-05",
    Category: "Sports & Fitness",
    rating: 4.2,
  },
  {
    id: 505,
    ProductName: "Cycling Helmet",
    ProductDesc: "Lightweight helmet with airflow design.",
    Price: 2499,
    Image: "https://picsum.photos/200?random=505",
    dateAdded: "2025-09-05",
    Category: "Sports & Fitness",
    rating: 4.5,
  },
  {
    id: 506,
    ProductName: "Boxing Gloves",
    ProductDesc: "Leather boxing gloves with padding.",
    Price: 2999,
    Image: "https://picsum.photos/200?random=506",
    dateAdded: "2025-09-06",
    Category: "Sports & Fitness",
    rating: 4.4,
  },
  {
    id: 507,
    ProductName: "Cricket Bat",
    ProductDesc: "English willow professional cricket bat.",
    Price: 6999,
    Image: "https://picsum.photos/200?random=507",
    dateAdded: "2025-09-06",
    Category: "Sports & Fitness",
    rating: 4.6,
  },
  {
    id: 508,
    ProductName: "Basketball",
    ProductDesc: "Official size indoor/outdoor basketball.",
    Price: 1299,
    Image: "https://picsum.photos/200?random=508",
    dateAdded: "2025-09-06",
    Category: "Sports & Fitness",
    rating: 4.3,
  },
  {
    id: 509,
    ProductName: "Skipping Rope",
    ProductDesc: "Adjustable speed jump rope.",
    Price: 799,
    Image: "https://picsum.photos/200?random=509",
    dateAdded: "2025-09-06",
    Category: "Sports & Fitness",
    rating: 4.2,
  },
  {
    id: 510,
    ProductName: "Resistance Bands",
    ProductDesc: "Set of 5 resistance bands for workout.",
    Price: 1499,
    Image: "https://picsum.photos/200?random=510",
    dateAdded: "2025-09-06",
    Category: "Sports & Fitness",
    rating: 4.4,
  },
];

import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "../models/Product.js";

dotenv.config();

const MONGO_URI = process.env.MONGO_DB_STRING;

mongoose
  .connect("mongodb://127.0.0.1:27017/ecommerce")
  .then(async () => {
    console.log("MongoDB connected");

    await Product.deleteMany(); // clear old
    await Product.insertMany(items); // insert new

    console.log("Sample products inserted ✅");
    process.exit();
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
